### ISSUE TITLE
Distribute query among peers (`/query`)

### ISSUE THREAD

**Issue by jneidel** [htw-projekt-p2p-volltextsuche/p2p#1]
**Todos**

- [ ] hash function (simple)
- [ ] p2p implementation
- [ ] http server (Emma?)
- [ ] send to volltextsuche (Emma?)

**Public Questions**

- [ ] another 1-2 servers for testing?
- [ ] define query structure
- [ ] define speeches structure

**Private Questions**

- [ ] customization of a hash function?
- [ ] chord/pastry java implementation?
- [ ] http server package?
- [ ] json in java?

**Comment by jneidel** [comment]
Irrelevant due to architectural changes.
